// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdbiunkwkhczwweirbep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkYml1bmt3a2hjend3ZWlyYmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDUxMTAsImV4cCI6MjA2MjYyMTExMH0.TX63OvDeM0Tt9OyOTCkloXhAH5s0Bhhrmur4tiatIHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);